export { AddUserLessonModel, UpdateUserLessonModel } from './user-lesson.model';
export { FacultyModel, AddFacultyModel, UpdateFacultyModel } from './faculty.model';
export { LocationModel, AddLocationModel, UpdateLocationModel } from './location.model';
export { DepartmanModel, AddDepartmanModel, UpdateDepartmanModel } from 'src/app/models/departman.model';
export { UserModel, AddUserModel, UpdateUserModel } from 'src/app/models/user.model';
export { LessonModel, AddLessonModel, UpdateLessonModel } from './lesson.model';
export { ConstraintModel, AddConstraintModel, UpdateConstraintModel } from 'src/app/models/constraint.model';
export { LoginModel } from './login.model';
export { ListUserModel } from './list-user.model';
export { AddDepartmentLessonModel } from './department-lesson.model';
export { UpdateDepartmentLessonModel } from './department-lesson.model';